#define DIR_TYPE models
#define INSTALL_TO models/cogHQ

#begin flt_egg
  #define SOURCES $[wildcard *.flt]
#end flt_egg

#begin maya_egg
  #define SOURCES $[wildcard *.mb]
#end maya_egg

// gagTank was moved for CogThief Game to phase 4
#begin install_egg
  #define SOURCES \
    gagTank.egg
  #define PHASE 4
#end install_egg

// Begin cogHQ
#begin install_egg
  #define SOURCES \
    Elevator.egg alphaCone2.egg\
    platform1.egg metalCrate.egg FloorWear.egg \
    FactoryGearB.egg metal_crateB.egg \
    square_stomper.egg \
    woodCrate_cube.egg woodCrateB.egg \
    CogDoor_Button.egg FactoryGearBpost.egg \
    StairTen3060_15wide.egg StairTen45.egg StairTen3060.egg \
    CogDoorHandShake.egg sellbotHQsign.egg \
    PaintMixer.egg BossRoomHQ.egg cube_tenfoot.egg \
    // Final model names
    SellbotFactoryExterior.egg SellbotHQLobby.egg SellbotHQExterior.egg SelbotLegFactory.egg \
    cog_sky.egg cogHQ_elevator.egg
  #define PHASE 9
#end install_egg

// Begin cogHQ phase 6
#begin install_egg
  #define SOURCES \
    SmokeStack_simple.egg WaterTowerSimple.egg Cog_Tunnel.egg
  #define PHASE 6
#end install_egg

// Begin cashbotHQ phase 10
#begin install_egg
  #define SOURCES \
    CashBotShippingStation.egg CashBotLocomotive.egg mintElevator.egg \
    CashBotBoxCar.egg CashBotTankCar.egg CashBotFlatCar.egg \
    VaultLobby.egg MidVault.egg EndVault.egg CashBotBossEyes.egg \
    CFOElevator.egg DoubleMoneyStack.egg CBMetalCrate2.egg RoundShadow.egg \
    SquareShadow.egg
  #define PHASE 10
#end install_egg

#begin install_egg
  // These egg files were generated by hand.
  #define SOURCES \
    CBLightning.egg CBMagnet.egg CBSafe.egg CBCraneArm.egg \
    CBCraneControls.egg CBCraneStick.egg
  #define PHASE 10
#end install_egg
